<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHxSEBsd\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHxSEBsd/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerHxSEBsd.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerHxSEBsd\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerHxSEBsd\appAppKernelProdContainer([
    'container.build_hash' => 'HxSEBsd',
    'container.build_id' => '5feeae3f',
    'container.build_time' => 1698155141,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHxSEBsd');
