<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDxtp6uO\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDxtp6uO/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerDxtp6uO.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerDxtp6uO\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerDxtp6uO\appAppKernelProdContainer([
    'container.build_hash' => 'Dxtp6uO',
    'container.build_id' => 'cfe5dfe9',
    'container.build_time' => 1698322526,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDxtp6uO');
